# Generated by Django 4.1.7 on 2023-04-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playstoreapp',
            name='package_detail',
            field=models.JSONField(null=True),
        ),
    ]
